### ISSUE TITLE
nullptr/cmake issue

### ISSUE THREAD

**Issue by Zacharyprime** [kipr/libwallaby#151]
We made an update to the CMake configuration that enforces C++11 mode over C++0.
It also now uses [CMAKE_CXX_STANDARD](http://www.cmake.org/cmake/help/v3.1/variable/CMAKE_CXX_STANDARD.html) which was introduced in cmake 3.1; this also causes a minor inconvenience because we are still stuck on Debian Jessie, which is obsolete and cannot pull updated packages for cmake 3.1 without some finagling.

This was a step in the right direction, but it has caused some other problems with the standard changes between C++11 and C++0 mode.

I ran into this while working on a different issue. A temporary solution is to paste the old cmake C++11 handling back in.

It shouldn't be too difficult to fix, I'm mainly leaving this as a reminder so I can finish solving the first issue I was doing.

Example of one of the errors produced:
```bash
/home/pi/got2/libwallaby/src/digital_c.cpp:13:38: error: ‘nullptr’ was not declared in this scope
  return Private::digital_value(port, nullptr);
                                      ^
Determining the scope of groups...
/home/pi/got2/libwallaby/src/digital_c.cpp: In function ‘int get_digital_value(int)’:
/home/pi/got2/libwallaby/src/digital_c.cpp:23:39: error: ‘nullptr’ was not declared in this scope
  return (Private::digital_value(port, nullptr) ? 1 : 0);
                                       ^
Sorting lists...
/home/pi/got2/libwallaby/src/digital_c.cpp: In function ‘int get_digital_output(int)’:
/home/pi/got2/libwallaby/src/digital_c.cpp:33:40: error: ‘nullptr’ was not declared in this scope
  return (Private::digital_output(port, nullptr) ? 1 : 0);

```

Old Version:
```cmake
# C++11
# http://www.guyrutenberg.com/2014/01/05/enabling-c11-c0x-in-cmake/
include(CheckCXXCompilerFlag)
CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)
CHECK_CXX_COMPILER_FLAG("-std=c++0x" COMPILER_SUPPORTS_CXX0X)
if(COMPILER_SUPPORTS_CXX11)
	add_definitions(--std=c++11)
elseif(COMPILER_SUPPORTS_CXX0X)
	add_definitions(--std=c++0x)
else()
	message(STATUS "The compiler ${CMAKE_CXX_COMPILER} has no C++11 support. Please use a different C++ compiler.")
endif()
```

New Version:
```cmake
# C++11
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
```

**Comment by Zacharyprime** [comment]
It's worthwhile to keep this issue in your bookmarks in order to build on <=26.1 because those are still stuck on jessie.

But there isn't actually something that needs to be fixed, we just need to get debian buster fully working so we can use cmake >=3.1.
